<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;

class AddL240ToLanguagesTable extends Migration
{
    /**
     * Run the migrations.
     *
     * @return void
     */
    public function up()
    {
        Schema::table('languages', function (Blueprint $table) {
            $table->text('l240')->after('l239')->nullable();
            $table->text('l241')->after('l240')->nullable();
            $table->text('l242')->after('l241')->nullable();
            $table->text('l243')->after('l242')->nullable();
            $table->text('l244')->after('l243')->nullable();
            $table->text('l245')->after('l244')->nullable();
            $table->text('l246')->after('l245')->nullable();
            $table->text('l247')->after('l246')->nullable();
            $table->text('l248')->after('l247')->nullable();
            $table->text('l249')->after('l248')->nullable();
            $table->text('l250')->after('l249')->nullable();
            //
            $table->text('l251')->after('l250')->nullable();
            $table->text('l252')->after('l251')->nullable();
            $table->text('l253')->after('l252')->nullable();
            $table->text('l254')->after('l253')->nullable();
            $table->text('l255')->after('l254')->nullable();
            $table->text('l256')->after('l255')->nullable();
            $table->text('l257')->after('l256')->nullable();
            $table->text('l258')->after('l257')->nullable();
            $table->text('l259')->after('l258')->nullable();
            $table->text('l260')->after('l259')->nullable();
            $table->text('l261')->after('l260')->nullable();
            //
            $table->text('l262')->after('l261')->nullable();
            $table->text('l263')->after('l262')->nullable();
            $table->text('l264')->after('l263')->nullable();
            $table->text('l265')->after('l264')->nullable();
            $table->text('l266')->after('l265')->nullable();
            $table->text('l267')->after('l266')->nullable();
            $table->text('l268')->after('l267')->nullable();
            $table->text('l269')->after('l268')->nullable();
            $table->text('l270')->after('l269')->nullable();
            $table->text('l271')->after('l270')->nullable();
            //
            $table->text('l272')->after('l271')->nullable();
            $table->text('l273')->after('l272')->nullable();
            $table->text('l274')->after('l273')->nullable();
            $table->text('l275')->after('l274')->nullable();
            $table->text('l276')->after('l275')->nullable();
            $table->text('l277')->after('l276')->nullable();
            $table->text('l278')->after('l277')->nullable();
            $table->text('l279')->after('l278')->nullable();
            $table->text('l280')->after('l279')->nullable();
            $table->text('l281')->after('l280')->nullable();
            $table->text('l282')->after('l281')->nullable();
            //
            $table->text('l283')->after('l282')->nullable();
            $table->text('l284')->after('l283')->nullable();
            $table->text('l285')->after('l284')->nullable();
            $table->text('l286')->after('l285')->nullable();
            $table->text('l287')->after('l286')->nullable();
            $table->text('l288')->after('l287')->nullable();
            $table->text('l289')->after('l288')->nullable();
            $table->text('l290')->after('l289')->nullable();
            $table->text('l291')->after('l290')->nullable();
            $table->text('l292')->after('l291')->nullable();
            $table->text('l293')->after('l292')->nullable();
            //
            $table->text('l294')->after('l293')->nullable();
            $table->text('l295')->after('l294')->nullable();
            $table->text('l296')->after('l295')->nullable();
            $table->text('l297')->after('l296')->nullable();
            $table->text('l298')->after('l297')->nullable();
            $table->text('l299')->after('l298')->nullable();
            $table->text('l300')->after('l299')->nullable();
            $table->text('l301')->after('l300')->nullable();
            $table->text('l302')->after('l301')->nullable();
            $table->text('l303')->after('l302')->nullable();
            $table->text('l304')->after('l303')->nullable();
            $table->text('l305')->after('l304')->nullable();
        });
    }

    /**
     * Reverse the migrations.
     *
     * @return void
     */
    public function down()
    {
        Schema::table('languages', function (Blueprint $table) {
            $table->dropColumn('l240');
            $table->dropColumn('l241');
            $table->dropColumn('l242');
            $table->dropColumn('l243');
            $table->dropColumn('l244');
            $table->dropColumn('l245');
            $table->dropColumn('l246');
            $table->dropColumn('l247');
            $table->dropColumn('l248');
            $table->dropColumn('l249');
            $table->dropColumn('l250');
            //
            $table->dropColumn('l251');
            $table->dropColumn('l252');
            $table->dropColumn('l253');
            $table->dropColumn('l254');
            $table->dropColumn('l255');
            $table->dropColumn('l256');
            $table->dropColumn('l257');
            $table->dropColumn('l258');
            $table->dropColumn('l259');
            $table->dropColumn('l260');
            $table->dropColumn('l261');
            //
            $table->dropColumn('l262');
            $table->dropColumn('l263');
            $table->dropColumn('l264');
            $table->dropColumn('l265');
            $table->dropColumn('l266');
            $table->dropColumn('l267');
            $table->dropColumn('l268');
            $table->dropColumn('l269');
            $table->dropColumn('l270');
            $table->dropColumn('l271');
            //
            $table->dropColumn('l272');
            $table->dropColumn('l273');
            $table->dropColumn('l274');
            $table->dropColumn('l275');
            $table->dropColumn('l276');
            $table->dropColumn('l277');
            $table->dropColumn('l278');
            $table->dropColumn('l279');
            $table->dropColumn('l280');
            $table->dropColumn('l281');
            $table->dropColumn('l282');
            //
            $table->dropColumn('l283');
            $table->dropColumn('l284');
            $table->dropColumn('l285');
            $table->dropColumn('l286');
            $table->dropColumn('l287');
            $table->dropColumn('l288');
            $table->dropColumn('l289');
            $table->dropColumn('l290');
            $table->dropColumn('l291');
            $table->dropColumn('l292');
            $table->dropColumn('l293');
            //
            $table->dropColumn('l294');
            $table->dropColumn('l295');
            $table->dropColumn('l296');
            $table->dropColumn('l297');
            $table->dropColumn('l298');
            $table->dropColumn('l299');
            $table->dropColumn('l300');
            $table->dropColumn('l301');
            $table->dropColumn('l302');
            $table->dropColumn('l303');
            $table->dropColumn('l304');
            $table->dropColumn('l305');
        });
    }
}
